### ISSUE TITLE
Homogeneity of content & structure

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-architecture#10]
Section 3.1. "Component Roles" focusses on three terms:
- 3.1.1. Posture Assessment Information Provider
- 3.1.2. Posture Assessment Information Consumer
- 3.1.3. Controller

Maybe the structure and content of this three subsection could be better aligned?

For example, 3.1.1 mentions "The Consumer implements the capabilities and functions that must be handled to share or provide Posture Assessment information.", but then no functions are highlighted. The only subsection that explicitly highlights functions is 3.1.3. This might leave the impression that functions are Control (or Management) Plane specific, which seems to contradict the text in 3.1.1.

There also seems to be further, rather specific content in the subsections that might not be subsection-specific. For example: on one hand 3.1.1. highlights the use of standard data models and/or protocols in contrast to non-standard data models and/or protocols, or the use of filter expressions regarding requests. On the other hand, 3.1.2. highlights the discovery of capabilities or the scope of posture attributes requested.

Maybe the structure of the text could be improved by moving basic concepts, such as requests/responses, functions and their corresponding interfaces on the data plane and management plane, the inclusion/coexistence of native data models and protocols and the SACM data models and protocols, etc. into their own subsections outside the role section that elaborates on provider, consumer and controller?

**Comment by llorenzin** [comment]
Resolution - revert "posture assessment information provider/consumer" to "provider/consumer" based on the conversation about information sharing in the 7/20 F2F
Henk will clarify the rest

**Comment by llorenzin** [comment]
Reverted to provider/consumer in -09
Incorporated Henk's proposed text into 3
Reorganized content into controller types (broker/proxy/repository) and provider/consumer types (collector, evaluator, etc.), control plane functions (authentication, authorization, etc.), data plane functions (publish, subscribe, query)

**Comment by llorenzin** [comment]
Henk is okay with closing this issue - he will open new issues if needed.
