### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#11]
version -03

What is the difference between a "reference architecture" and just an "architecture".

**Comment by llorenzin** [comment]
Personally, I think of an architecture as a generic model and a reference architecture as a more detailed / specific exemplary instantiation of the generic model, so I would change this to just "architecture".  I don't know if that's a common understanding, though, so would prefer a group consensus before revising.

-----Original Message-----

**Comment by jimsch** [comment]
I would vote for removing 'reference'.

**Comment by ncamwing** [comment]
I'm good for removing reference as well...

**Comment by llorenzin** [comment]
Resolution - remove reference

**Comment by llorenzin** [comment]
Removed in -04
