### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#12]
Version -03

I suggest fixing the grammar in the last sentence.   You are either doing the interfaces between the components, in which case 'their interfaces' is fine, but punctuation is needed before 'defined'  ('their interfaces; defined for the collection'.  Or you it should be 'the interfaces defined'.  I think the latter is better.

**Comment by llorenzin** [comment]
I agree, and I'd further simplify to "the architecture, components, and interfaces defined".  Revised in -04.

-----Original Message-----
