### ISSUE TITLE
Section 1 - Introduction

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#13]
version -03

The addition of some references to the first two sentences would be appreciated.  Having some ability to find out what we are contrasting to is going to be useful.

**Comment by llorenzin** [comment]
I'm happy to add any specific references the group would like to suggest.

-----Original Message-----

**Comment by jimsch** [comment]
I am afraid that I don't know what the world of this is. Based on the messages over the list I assume that a reference to NEA, OVAL, TNC and maybe some others would be in order.

**Comment by llorenzin** [comment]
Resolution - add "(including, but not limited to, NEA, TCG TNC, SCAP, SWIDs, XMPP, etc.)" after "data models and protocols"

**Comment by llorenzin** [comment]
Fixed in -04
