### ISSUE TITLE
Section 2 - Problem Statement

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#15]
Version -03

this text currently outlines a problem, but not a problem statement.  I would like to see some additional text added that says what
this document (or group of documents) is actually trying to do.   Thus at
the end of the first paragraph something about - We are creating a data model that will allow for administrators to share with others and to use data from others in a standardized method.  (is this is in this document or should a pointer be added to the data model document?)

**Comment by llorenzin** [comment]
Resolution - add "We are standardizing an information model, data models, operations, and transports that will allow for administrators to share with others and to use data from others interoperably." to section 2.

**Comment by llorenzin** [comment]
Fixed in -04
