### ISSUE TITLE
Section 3 - Architectural Overview

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#16]
Version -03

I am not sure of the difference between processed and assessed.  I assume that the first means that it is "transformed" according to some standard while the second means comparing it against some standard.  Perhaps a better word than processed can be found.

**Comment by llorenzin** [comment]
"Processed" is intended to encompass any parsing or manipulation of the data required before assessment - things like normalization, translation, aggregation, etc.  Given that context, do you have an alternative you'd prefer to suggest?  I'm happy to use something that will more clearly communicate the concept if we can find a better option.

-----Original Message-----

**Comment by henkbirkholz** [comment]
Maybe the processes that support the goal of target endpoint assessment could be better highlighted and elaborated, in general? I am not sure if the architecture is the right place for that. In any case, the "evolution" of data during things, such as normalization, aggregation and correlation, is probably a basic process SACM builds on.

**Comment by llorenzin** [comment]
Resolution - add "(e.g. normalization, translation, aggregation, etc.)" after processed

**Comment by llorenzin** [comment]
Done in -04
