### ISSUE TITLE
open question at the end of section 2

### ISSUE THREAD

**Issue by sacm** [sacmwg/draft-ietf-sacm-architecture#2]
 Why does the charter not suffice?
 What is the purpose of inserting this section in this draft?

The answer is that the charter is a temporary document visible and accessible while the WG is active (and subject to change during this period) but tends to disappeared when the WG is concluded. A recap of the problem statement in the introductory sections of the architecture document provides background information for the architecture that follows and can be very useful for understanding some of the fundamental decisions.

**Comment by jimsch** [comment]
This appears to have been addressed in the -03 version of the draft.
