### ISSUE TITLE
Figure 1- Simple Architecture Model

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#21]
Version -03

I have a minor problem with the picture.  I think that a "Repository" is a Provider and not a Controller.  (I don't know if I also think that a "Repository" is also a consumer or not - It would depend if it was actively looking for data or not.)  The controller plane controls access to data but not data itself.

**Comment by llorenzin** [comment]
We discussed this in the original development of the architecture draft and came to consensus that a controller can either be a broker (no data interaction, simply providing control functions for clients to find each other and share information), a proxy (receiving a consumer request, retrieving data from the appropriate providing, and sharing it with the requestor), or a repository (receiving data from providers, storing it, and sharing it with consumers upon request).  Each of these modes enables a different (sometimes overlapping) set of use cases.

-----Original Message-----

**Comment by henkbirkholz** [comment]
The "center piece" in the figure - the controller - represents different sets of data plane and control plane functions (and maybe even management plane functions). Three separate mixes of functions to be precise, which are labeled broker, proxy and repository.
Only the broker (probably) contains only control plane functions. The repository most certainly contains a considerable set of data plane functions with interfaces that can act as provider and consumer.

**Comment by sacm** [comment]
While I don’t strictly disagree with the broker/proxy/repository model, I have always had the same concern that Jim just raised. A repository may be interacted with in either plane. In addition to interactions on the control plane, it can also act as a component of the data plane where it is at minimum a provider of data. It is also likely that it may be considered a consumer of published (and maybe requested) data. The architecture diagram does not draw out these dimensions.

**Comment by jimsch** [comment]
To me a repository can occupy positions on multiple places in the picture.  But this is true of things like evaluators as well.  A repository is going to be a consumer - components can publish data to it.  It can be a provider - components can extract data from it.  It might also have functionality of a broker or proxy as well - it can look for data it has been asked for but does not currently have on behalf of a consumer.  This does not mean that it should be placed into the middle.  It means that there is a component that can live in multiple locations.  The pure concepts of a proxy and a broker are definitely control items - they are going to do redirection of conversations.   This is not true of a repository.

**Comment by henkbirkholz** [comment]
I agree with your observation, I think. Maybe a repository could be a prominent example of a SACM component that is potentially composed of a variety of functions that enable it to act as a provider/publisher, consumer/subscriber, broker or even as proxy in some cases (therefore, potentially placing it at multiple possible positions or planes in the point of view illustrated by the picture).

Maybe this could also imply that there could be different variants of repositories with more powerful sets or more basic sets of functions, depending on their purpose or the environment (it might not have to act as a broker or proxy on the control plane in some scenarios)?

**Comment by david-waltermire** [comment]
+1

**Comment by ncamwing** [comment]
So, is the suggestion converging on removing "repository" from the "Control plane" arrow and adding "Repository" as another SACM component (that can be either a publisher or subscriber)?

**Comment by llorenzin** [comment]
I'm happy to clarify that a repository can also be either a consumer or a provider (or both) in the SACM components descriptions. However, I do not agree with removing repository from the control plane.  The repository model of controller supports the loose coupling and unsolicited publication requirements - SACM publishers can publish information to a repository at will, rather than in response to a request, and that information is then available for any (authorized) consumer to retrieve without any dependency on the original publisher being available or even known. (The Ice Station Zebra use case is one of the best-fit use cases for a repository as controller.) Also, the repository model is one of the few running-code implementations - and the only standards-based example - of existing real-world SACM-style security automation.

**Comment by llorenzin** [comment]
Resolution - remove the labels broker/proxy/repository from figure 1

**Comment by llorenzin** [comment]
Done in -04
