### ISSUE TITLE
Section 3.1.2 - Posture Assement Information Consumer

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#22]
version -03

s/in order to facilitate/in order to create/

s/evaluated or assessed state/evaluation results/   My understanding is that assessed stated is the raw information.  There appears to be nothing in the terminology draft for a "computed" state which is a combination or transformation of attributes into a new attribute - but not from an evaluation step.

**Comment by ncamwing** [comment]
Hmm, are you suggested we use "computed"?  I don't think we use it though "evaluate or assess" seem to imply that; e.g. a transformation of attributes into a new one...

**Comment by llorenzin** [comment]
Resolution - s/facilitate/enable
s/evaluated or assessed state / evaluation result

**Comment by llorenzin** [comment]
Done in -04
