### ISSUE TITLE
Section 3.1.3 - Controller

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#24]
Version -03

First - please edit the run on sentence that starts this section.  Removing some of the 'and' and moving to commas is needed.

I am having a problem with the concept of a single controller given the breadth of the responsibilities that are being dumped into this single component.   The functionality of "the controller" could be spread over a number of components. However the first sentence appears to make this a every controller has all of this functionality issue.

**Comment by ncamwing** [comment]
Will work on fixing the sentence....the notion was to define it as an abstract controller that provides the functions but I think from an implementation it can be a single implementation or a set of services that can also be distributed (and federated) to provide scalability.  If you have suggestions on fixing the sentence, would appreciate the help.

**Comment by llorenzin** [comment]
Resolution - grammar fix, find a way to say that not every controller will instantiate every one of these functions.

**Comment by ncamwing** [comment]
This was somewhat done in -v04 and I've cleaned it up a bit more in v05

**Comment by jimsch** [comment]
This issue has been resolved.
