### ISSUE TITLE
editorial issues in section 3.1.3

### ISSUE THREAD

**Issue by sacm** [sacmwg/draft-ietf-sacm-architecture#3]
s/The introduction of the controller supports use cases/ The controller supports use cases/
s/Consumer’s/Consumers/
s/Provider’s/Providers/
s/interface “C” shown in Figure 1 demonstrates/ interface “C” shown in Figure 1 illustrates/

**Comment by llorenzin** [comment]
Fixed in the 03 we'll be posting this weekend - thanks!
