### ISSUE TITLE
Section 8 - Security Considerations

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#31]
version -03

Similarly, to avoid potential message tampering, confidentiality should also be provided.

tampering is prevented by integrity not by encryption.   If you are trying to justify doing encryption, then you need a different reason than this.

**Comment by ncamwing** [comment]
Hmmm....I meant integrity.  Confidentiality I think is a should and needed only for privacy so will need to clarify this.  Thanks for catching it.

**Comment by jimsch** [comment]
Fixed in version -04
