### ISSUE TITLE
Figure 1- Simple Architecture Model - Regression

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#32]
Version -04

You regressed to using C rather than Cs for consumer.  THis is a problem because you are using A, B and C for data flows as well.

**Comment by henkbirkholz** [comment]
As an additional very minor detail, Pr (or another two letter abbrevation) instead of P could be used for Provider to make it a little more consistent.

**Comment by llorenzin** [comment]
Nancy will update - changing C to Cs and P to Pr

**Comment by jimsch** [comment]
Fixed in -04
