### ISSUE TITLE
question about the title for section 3.1.3

### ISSUE THREAD

**Issue by djhaynes** [sacmwg/draft-ietf-sacm-architecture#36]
Should the title for section 3.1.3 should read "Types of Providers and Consumers" instead of "Types of Providers and Controllers"?

**Comment by sacm** [comment]
Hi Danny,

+1

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by henkbirkholz** [comment]
Yes, that's a typo there.

Cheers,

Henk

**Comment by ncamwing** [comment]
Agreed and will fix in the next revision.

**Comment by jimsch** [comment]
Fixed and published in -04
