### ISSUE TITLE
broker / proxy terminology issue

### ISSUE THREAD

**Issue by sacm** [sacmwg/draft-ietf-sacm-architecture#4]
> In order to understand the sentence ‘a controller may also provide the proxy or broker (and possibly routing) function in the data plane’ I went back to the terminology document.

What I found is that the following terms are defined:

> Broker - An entity providing and/or connecting services on the behalf of other architectural components.
> Proxy - An architectural component providing functions, information, or services on behalf of another component, which is not directly participating in the architecture.

These definitions seem to need more work. They are partially redundant – is this by design? Proxy is not ‘participating in the architecture’? Then how is it between the 2-3 fundamental functions of the controller? There needs to be more work in the terminology document I guess.

**Comment by llorenzin** [comment]
I'm adding clarifying detail to the control-plane capabilities section of the architecture draft. Once the group reviews that, if it's sufficiently clear, then I think we need to update the terminology draft to include concise definitions consistent with the usage in the architecture draft, with the architecture draft continuing to provide the details around the functionality.

**Comment by llorenzin** [comment]
Fixed in -03
