### ISSUE TITLE
superfluous text?

### ISSUE THREAD

**Issue by sacm** [sacmwg/draft-ietf-sacm-architecture#5]
> TODO ‐ add text around the usage of various protocols for endpoint

data collection (SNMP, NETCONF, etc.?)

> do we really need these in an architecture document?

**Comment by llorenzin** [comment]
This todo came out of the IETF 90 minutes:
o   The architecture considers the use of various protocols for endpoint data collection (i.e. NETCONF, SNMP, etc.), but this is implied and the text of the draft should be updated.

**Comment by llorenzin** [comment]
Resolution - text in -03 is fine
