### ISSUE TITLE
Clarify meaning of "capabilities" and "roles"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-architecture#8]
Henk raised this issue during the 2015-04-17 endpoint ID design meeting.  The present architecture draft doesn't clearly articulate what a "capability" and sometimes (potentially) confuses "capability" with "role".  These terms and their use should be clarified.

**Comment by llorenzin** [comment]
Resolution
- change existing use of "capability" to "function"
- add a discussion of "capability" as being able to talk a specific data model, data operations, or SACM transport
- be specific about what kind of capability / what kind of function we're talking about
- data plane function / control plane function reside in the SACM component
- data plane capabilities / control plane capabilities can be discovered via querying the controller

**Comment by llorenzin** [comment]
Started fixes in -04
- changed existing use of "capability" to "function"
- stubbed in a section for "capability" / discovery 
- clarifications around functions

**Comment by llorenzin** [comment]
Henk is okay with closing this issue.

**Comment by jimsch** [comment]
Given that the comment says that it was started in -04 has this been finished yet?
