### ISSUE TITLE
publish/subscribe model and "ad-hoc" queries

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-architecture#9]
It seems that SACM targets to include a publish/subscribe model (as a specialization of the provider/consumer model) as a part of the architecture. Is this correct?

If this is indeed intended to be a core concept, the structure of the draft needs improvement, as this concept is barely introduced at the moment and bits and pieces relating to it are scattered throughout the text (sometimes quite surprisingly so). E.g. The term Broker is introduced via a diagram (section 3) and mentioned the first time at the end of section 3.1.3. mid-sentence. The term Subscription (or anything labeled "subscr*") is mentioned only once as a side comment in parentheses, etc.

A potential remedy could be an better aggregated (and early) introduction of the concept in the architecture draft?

If it is not a core concept of the architecture (leaving - as it is - Controller/Provider/Consumer as the remaining core terms), a consolidated paragraph in the text could highlight the relationship to the Publish/Subscribe concept (and maybe refer to IM and DM drafts).

The same applies to "ad-hoc queries", which are only mention implicitly via the term "one-time query" near to the introduction of "subscription" in 3.1.2.

**Comment by llorenzin** [comment]
Resolution - add a sentence to 3 to describe the high-level SACM operations (publish, query, subscribe).

**Comment by llorenzin** [comment]
Fixed in -04 - added to description of functions

**Comment by llorenzin** [comment]
Henk to review and close or update
